[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "marketpipe"
version = "0.1.0"
description = "Lightweight CLI-based ETL for market data"
readme = "README.md"
authors = [{name = "MarketPipe"}]
requires-python = ">=3.9"
dependencies = [
    "typer[all]",
    "pandas",
    "duckdb",
    "pyarrow",
    "requests"
]

[project.scripts]
marketpipe = "marketpipe.cli:app"
