# ⚠️  ALPHA SOFTWARE WARNING: MarketPipe is in alpha development.
# Expect breaking changes and potential stability issues. This configuration
# format may change in future releases. Not recommended for production use.

alpaca:
  # Credentials are loaded from .env file automatically by the coordinator
  key: # Will be loaded from ALPACA_KEY in .env file
  secret: # Will be loaded from ALPACA_SECRET in .env file
  base_url: https://data.alpaca.markets/v1beta1  # Use v1beta1 for IEX free tier
  rate_limit_per_min: 200
  feed: iex  # Use "iex" for free tier, "sip" for paid subscription

symbols:
  - AAPL
  - GOOGL
  - MSFT

start: "2023-01-01"
end: "2023-01-02"
output_path: "./data"
compression: snappy
workers: 3

metrics:
  enabled: true
  port: 8000
