alpaca:
  # Credentials are loaded from .env file automatically by the coordinator
  key: # Will be loaded from ALPACA_KEY in .env file
  secret: # Will be loaded from ALPACA_SECRET in .env file
  base_url: https://data.alpaca.markets/v2
  rate_limit_per_min: 200

symbols:
  - AAPL
  - GOOGL
  - MSFT

start: "2023-01-01"
end: "2023-01-02"
output_path: "./data"
compression: snappy
workers: 3

metrics:
  enabled: true
  port: 8000
