alpaca:
  # Credentials are loaded from .env file automatically by the coordinator
  key: # Will be loaded from ALPACA_KEY in .env file
  secret: # Will be loaded from ALPACA_SECRET in .env file
  base_url: https://data.alpaca.markets/v2  # Use v2 API endpoints
  rate_limit_per_min: 200
  feed: iex  # Use "iex" for free tier, "sip" for paid subscription

<<<<<<< HEAD
output_path: data
compression: snappy
symbols: ["AAPL", "MSFT", "TSLA"]
start: 2025-06-04
end: 2025-06-04
=======
symbols:
  - AAPL
  - GOOGL
  - MSFT

start: "2024-01-02"
end: "2024-01-03"
output_path: "./data"
compression: snappy
>>>>>>> df1d1238a09e3b6e79502b59c928819d7d544643
workers: 3

metrics:
  enabled: true
  port: 8000
