alpaca:
  # Recommend loading credentials from environment variables for security
  key: ${ALPACA_KEY}
  secret: ${ALPACA_SECRET}
  base_url: https://data.alpaca.markets/v2
  rate_limit_per_min: 200

output_path: data
symbols: ["AAPL", "MSFT", "TSLA"]
start: 2024-01-02
end: 2024-01-02
workers: 3
compression: snappy

metrics:
  enabled: true
  port: 8000
