# MarketPipe Ingestion Configuration - Fixed Version
config_version: "1"

# Required: List of stock symbols to ingest
symbols: [AAPL]

# Required: Date range for ingestion (YYYY-MM-DD format)
# Using recent dates within valid range (30 days ago)
start: "2025-05-18"
end: "2025-05-23"

# Optional: Configuration parameters
batch_size: 1000        # Number of bars per API request
provider: alpaca        # Market data provider
feed_type: iex         # Data feed type (iex for free)
output_path: ./data    # Output directory for data files
workers: 1             # Number of worker threads
